### ISSUE TITLE
Array objects cannot be used as a contract parameter

### ISSUE THREAD

**Issue by Mercurii7** [ngdenterprise/neo-test#19]
When passing an Array object as a contract parameter in the test-harness, the following error is shown:

```
    Outcome: Failed
    Error Message:
    System.ArgumentException : Value does not fall within the expected range. (Parameter 'obj')
    Stack Trace:
       at Neo.VM.Helper.EmitPush(ScriptBuilder builder, Object obj)
   at NeoTestHarness.Extensions.CreateScript[T](DataCache snapshot, Expression`1[] expressions) in /_/src/test-harness/Extensions.cs:line 54
   at NeoTestHarness.Extensions.LoadScript[T](ApplicationEngine engine, Expression`1[] expressions) in /_/src/test-harness/Extensions.cs:line 37
   at NeoTestHarness.Extensions.ExecuteScript[T](ApplicationEngine engine, Expression`1[] expressions) in /_/src/test-harness/Extensions.cs:line 24
```

Sample project: https://github.com/Mercurii7/neo-arrays

**Comment by devhawk** [comment]
This is a limitation of [`Neo.VM.Helpers.EmitPush(ScriptBuilder, object)`](https://github.com/neo-project/neo/blob/master/src/neo/VM/Helper.cs#L191). It can't handle Array types. I'm thinking the correct solution is to write a custom `ConvertParameter` method that takes an object and converts it to ContractParameter instances based on similar type checking to EmitPush (but that also handles all stack item types including Array)
